name: Trigger Sync in repo-1

on:
  push:
    branches:
      - main  # or whichever branch you want to track for changes in repo-2

jobs:
  trigger-sync:
    runs-on: ubuntu-latest

    steps:
    - name: Trigger sync in repo-1
      run: |
        curl -X POST https://api.github.com/repos/CONFEST-2026/confest-2026.github.io/dispatches \
          -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
          -d '{"event_type": "sync-fmics"}'
